import type { Metadata } from "next";

import { raleway_sans } from "@/utils/fonts/fontUtils";

import RootLayout from "@/components/layout/root/RootLayout";

import 'react-toastify/dist/ReactToastify.css';
import "./globals.css";
import "react-quill/dist/quill.snow.css";

export const metadata: Metadata = {
  title: "Trang chủ",
  description: "Generated by create next app",
};

export default function RootLayoutApp({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${raleway_sans.className} antialiased`}
      >
        <RootLayout>
          {children}
        </RootLayout>
      </body>
    </html>
  );
}
